# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0020_auto_20160425_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='upload_cv',
            field=models.FileField(upload_to='cvfiles'),
        ),
    ]
