# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0023_auto_20160425_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sec',
            name='school',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='srsec',
            name='school',
            field=models.CharField(max_length=40),
        ),
    ]
